[package]
name = 'pty'
version = '0.1.6'
authors = ['Hika Hibariya <hibariya@gmail.com>']
repository = 'https://github.com/hibariya/pty-rs'
homepage = 'https://github.com/hibariya/pty-rs'
license='MIT'
description='Fork with new pseudo-terminal (PTY)'
keywords = ['pty', 'tty', 'pseudo', 'terminal', 'fork']

[dependencies]
libc = '0.2'
nix = '0.4'
clippy = {version = '0.0', optional = true}

[features]
default = []
dev = ['clippy']
