[package]
name = "pty"
version = "0.1.1"
authors = ["Hika Hibariya <hibariya@gmail.com>"]
repository = "https://github.com/hibariya/pty-rs"
homepage = "https://github.com/hibariya/pty-rs"
license="MIT"
description='Fork with new pseudo-terminal (PTY)'

[dependencies]
libc='0.1'
